services:
  - type: web
    name: working-players
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
